FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && apt-get install -y potrace libcairo2 media-types libpango-1.0-0 libpangocairo-1.0-0

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .
COPY ./color_it_daily_agent color_it_daily_agent

CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port $PORT"]